# Generated by Django 5.0.1 on 2024-02-10 17:48

from django.db import migrations


def create_workstation_statuses(apps, schema_editor):
    WorkstationStatus = apps.get_model('workstation_coordinator', 'WorkstationStatus')
    WorkstationStatus.objects.create(name='In Preparation')
    WorkstationStatus.objects.create(name='In Cleanup')
    WorkstationStatus.objects.create(name='Active')
    WorkstationStatus.objects.create(name='In Use')
    WorkstationStatus.objects.create(name='Non-Functional')
    WorkstationStatus.objects.create(name='Archived')

def create_reservation_statuses(apps, schema_editor):
    ReservationStatus = apps.get_model('workstation_coordinator', 'ReservationStatus')
    ReservationStatus.objects.create(name='Pending')
    ReservationStatus.objects.create(name='Approved')
    ReservationStatus.objects.create(name='Rejected')
    ReservationStatus.objects.create(name='Active')
    ReservationStatus.objects.create(name='Cancelled')
    ReservationStatus.objects.create(name='Completed')


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_workstation_statuses),
        migrations.RunPython(create_reservation_statuses),
    ]
