# Generated by Django 5.0.1 on 2024-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0002_auto_20240210_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='additional_information',
            field=models.JSONField(null=True),
        ),
    ]
