# Generated by Django 5.0.1 on 2024-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0003_reservation_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxymapping',
            name='external_address',
        ),
        migrations.RemoveField(
            model_name='proxymapping',
            name='external_port',
        ),
        migrations.AddField(
            model_name='proxymapping',
            name='external_path',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstation',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
