# Generated by Django 5.0.1 on 2024-03-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0005_enginetype_remove_host_available_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstation_coordinator.engine'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='proxy_mapping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstation_coordinator.proxymapping'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstation_coordinator.workstation'),
        ),
    ]
