# Generated by Django 5.0.1 on 2024-04-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0006_workstation_engine_alter_reservation_proxy_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
