# Generated by Django 5.0.1 on 2024-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0007_alter_workstation_ip_address_alter_workstation_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
