# Generated by Django 5.0.1 on 2024-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0008_alter_workstation_ip_address_alter_workstation_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='additional_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
