# Generated by Django 5.0.1 on 2024-05-15 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0011_remove_workstation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-request_date']},
        ),
        migrations.AddField(
            model_name='proxymapping',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxymapping',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxymapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
