# Generated by Django 5.0.1 on 2024-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0012_alter_reservation_options_proxymapping_archived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxymapping',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='workstation',
            name='engine_internal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
