# Generated by Django 5.0.1 on 2024-05-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0015_reservation_last_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='status',
            field=models.CharField(choices=[('Cleanup', 'Cleanup'), ('Active', 'Active'), ('Setup', 'Setup'), ('Archived', 'Archiving'), ('Scheduled', 'Scheduled'), ('Broken', 'Broken')], default='Scheduled', max_length=200),
        ),
    ]
