# Generated by Django 5.0.1 on 2024-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0016_alter_workstation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='status',
            field=models.CharField(choices=[('Cleanup', 'Cleanup'), ('Active', 'Active'), ('Setup', 'Setup'), ('Archived', 'Archived'), ('Scheduled', 'Scheduled'), ('Broken', 'Broken')], default='Scheduled', max_length=200),
        ),
    ]
