# Generated by Django 5.0.1 on 2024-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0017_alter_reservation_status_alter_workstation_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
        migrations.DeleteModel(
            name='WorkstationStatus',
        ),
        migrations.AddField(
            model_name='proxymapping',
            name='looked_up',
            field=models.BooleanField(default=False),
        ),
    ]
