# Generated by Django 5.0.1 on 2024-06-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0018_delete_reservationstatus_delete_workstationstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Broken', 'Broken')], default='Pending', max_length=200),
        ),
    ]
