# Generated by Django 5.0.1 on 2024-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0019_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
