# Generated by Django 5.0.1 on 2024-06-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstation_coordinator', '0023_alter_workstation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['-last_status_update']},
        ),
    ]
